const tr = document.createElement("tr");
const tdLabel = document.createElement("td");
const tdInput = document.createElement("td");
tr.appendChild(tdLabel);
tr.appendChild(tdInput);
const label = document.createElement("label");
label.setAttribute("for", "ciclo");
label.nodeValue();
document.getElementById("boton").style.display = "none";
updateRows();
